spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/travelFeeManage?characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

server:
  port: 8098